### ISSUE TITLE
Extend `docker-login` to check for credentials store

### ISSUE THREAD

**Issue by jzaefferer** [sloppyio/cli#12]
For `sloppy docker-login`, we read `~/.docker/config.json` and upload it to our service, for authenticating private repositories. This usually works fine, but breaks when the file itself doesn't contain the credentials. On OSX, Docker can use the system keychain instead: https://github.com/docker/docker-credential-helpers#usage

Our API already checks for missing auth parameter, and now also checks if there's a credsStore property. It might still be better to catch that issue here (before sending the data anywhere).

For the osxkeychain, we could extend the CLI to get the credentials using the docker-credential-osxkeychain tool. The user is prompted with a keychain dialog in this case. This is how it works:
```
> echo "quay.io" | docker-credential-osxkeychain get
{"ServerURL":"","Username":"mwilz","Secret":"..."}
```

**Comment by zliw** [comment]
There also should be a similar helper for the wincred storage under windows. See
https://github.com/docker/docker-credential-helpers

**Comment by benjy** [comment]
Is there a workaround for this in the interim?
