### ISSUE TITLE
Distribute via npm

### ISSUE THREAD

**Issue by jzaefferer** [sloppyio/cli#17]
To make our CLI easier to install, at least for developers using npm, we should support installing our CLI via `npm install -g sloppy`

Start testing with some "private" namespace. If that works fine, find a good available name, or get the sloppy name. Currently this is in use: https://www.npmjs.com/package/sloppy - since the package doesn't even have a readme, it should be possible to claim / take over the name. With no dependencies its not going to be the next leftpad.

**Comment by jzaefferer** [comment]
Contacted the author of that package, following npm's rules for name disputes: https://www.npmjs.com/policies/disputes

**Comment by KevinBusse** [comment]
I strongly oppose the idea of publishing a (go) binary on a distribution platform for Node.js packages.

Same goes for:

- `gem install sloppy`
- `pip install sloppy`
- `php composer.phar install sloppy`
- `marven install sloppy`
- ...

Alternatively similar to the brew installation it should be made available as rpm/deb packages for Linux and chocolatey package for Windows.

**Comment by jzaefferer** [comment]
Yeah, you're right. #15 covers Homebrew. We can also look into rpm/deb and chocolatey.

PS: Trying to claim the `sloppy` package resulted in the owner finally publishing their 'Node.js micro-services framework'. Oh well
