### ISSUE TITLE
Disable volume checks or virtual mapping

### ISSUE THREAD

**Issue by TomRiedl** [sloppyio/cli#32]
Is it possible to disable the volume checks or combine volumes/map them virtually?

E.g. if you use [Zabbix Server](https://hub.docker.com/r/zabbix/zabbix-server-pgsql/) the following error appears:
`error: Unsupported change for project monitoring-develop Could not update project. App "server" needs the following volumes: /usr/lib/zabbix/alertscripts, /usr/lib/zabbix/externalscripts, /var/lib/zabbix/enc, /var/lib/zabbix/mibs, /var/lib/zabbix/modules, /var/lib/zabbix/snmptraps, /var/lib/zabbix/ssh_keys, /var/lib/zabbix/ssl/certs, /var/lib/zabbix/ssl/keys, /var/lib/zabbix/ssl/ssl_ca; Please add those volumes`

As you can see it is just `/var/lib/zabbix/` + some specific directories. Currently I only see the chance to create own volumes for each entry, which results in 80 GiB of volumes for some KiBs of data.
Some of these directories are optional so they don't even have to exist.

**Comment by jzaefferer** [comment]
Looks like this is "by design" of that image. Maybe building a custom image on top, that only specifies `/var/lib/zabbix` as a volume could help?

That said, this isn't an issue with the CLI. For more support for sloppy.io, please contact support@sloppy.io (or use the support chat on the site)
